platform :ios, '10.0'

target 'reSwift_example' do
  use_frameworks!
  
  pod 'RealmSwift'
  pod 'ReSwift'

  target 'reSwift_exampleTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end