//
//  PersonAddWorker.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PersonAddStoreProtocol {
    func add(person: Person)
}

class PersonAddWorker: PersonAddStoreProtocol  {
    func add(person: Person) {
        RealmService.sharedInstance.add(object: person)
    }
}
