//
//  PersonAddConfigurator.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

extension PersonAddViewController: PersonAddPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension PersonAddInteractor: PersonAddViewControllerOutput {
}

extension PersonAddPresenter: PersonAddInteractorOutput {
}

class PersonAddConfigurator {
    
    static let sharedInstance = PersonAddConfigurator()
    
    private init() {}
    
    func configure(viewController: PersonAddViewController) {
        let router = PersonAddRouter()
        router.viewController = viewController
        
        let presenter = PersonAddPresenter()
        presenter.output = viewController
        
        let interactor = PersonAddInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
