//
//  PersonAddViewController.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PersonAddViewControllerInput {
    func dismissViewController()
}

protocol PersonAddViewControllerOutput {
    func add(_ request: PersonAdd.Add.Request)
    func cancelBarButtonTouched()
}

class PersonAddViewController: UIViewController {
    
    @IBOutlet var firstnameTextField: UITextField!
    @IBOutlet var lastnameTextField: UITextField!
    
    var output: PersonAddViewControllerOutput!
    var router: PersonAddRouter!
    
    override func awakeFromNib() {
        super.awakeFromNib()
        PersonAddConfigurator.sharedInstance.configure(viewController: self)
    }
    
    @IBAction func cancelBarButtonTouched(_ sender: Any) {
        output.cancelBarButtonTouched()
    }
    
    @IBAction func saveBarButtonTouched(_ sender: Any) {
        let request = PersonAdd.Add.Request(firstname: firstnameTextField.text, lastname: lastnameTextField.text)
        output.add(request)
    }
}

extension PersonAddViewController: PersonAddViewControllerInput {
    func dismissViewController() {
        navigationController?.dismiss(animated: true, completion: nil)
    }
}
