//
//  PersonAddInteractor.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PersonAddInteractorInput {
    func add(_ request: PersonAdd.Add.Request)
    func cancelBarButtonTouched()
}

protocol PersonAddInteractorOutput {
    func personAdded()
    func cancelBarButtonTouched()
}

class PersonAddInteractor: PersonAddInteractorInput {
    var output: PersonAddInteractorOutput!
    var worker: PersonAddWorker!
    
    var personAddWorker = PersonAddWorker()
    
    func add(_ request: PersonAdd.Add.Request) {
        if let firstname = request.firstname, let lastname = request.lastname, !firstname.isEmpty, !lastname.isEmpty {
            let person = Person(firstname: firstname, lastname: lastname, isCreated: NSDate())
            personAddWorker.add(person: person)
            output.personAdded()
        }
    }
    
    func cancelBarButtonTouched() {
        output.cancelBarButtonTouched()
    }
}
