//
//  PersonsViewController.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PersonsViewControllerInput {
    func show(viewModel: Persons.FetchPersons.ViewModel)
    func personsRemoved()
}

protocol PersonsViewControllerOutput {
    func updateView()
    func removePersons()
}

class PersonsViewController: UIViewController {
    
    @IBOutlet var tableView: UITableView!
    
    var output: PersonsViewControllerOutput!
    var router: PersonsRouter!
    var displayedPersons: [Persons.FetchPersons.ViewModel.DisplayPerson] = []
    
    override func awakeFromNib() {
        super.awakeFromNib()
        PersonsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        output.updateView()
    }
    
    @IBAction func removePersonsBarButtonTouched(_ sender: Any) {
        output.removePersons()
    }
}

extension PersonsViewController: PersonsViewControllerInput {
    func show(viewModel: Persons.FetchPersons.ViewModel) {
        displayedPersons = viewModel.displayedPersons
        tableView.reloadData()
    }
    func personsRemoved() {
        displayedPersons.removeAll()
        tableView.reloadData()
    }
}

extension PersonsViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
}

extension PersonsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedPersons.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath)
        let person = displayedPersons[indexPath.row]
        cell.textLabel?.text = "\(person.firstname) \(person.lastname)"
        if let date = person.isCreated {
            cell.detailTextLabel?.text = date
        }
        return cell
    }
}

