//
//  PersonsConfigurator.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

extension PersonsViewController: PersonsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension PersonsInteractor: PersonsViewControllerOutput {
}

extension PersonsPresenter: PersonsInteractorOutput {
}

class PersonsConfigurator {
    
    static let sharedInstance = PersonsConfigurator()
    private init() {}
    
    func configure(viewController: PersonsViewController) {
        let router = PersonsRouter()
        router.viewController = viewController
        
        let presenter = PersonsPresenter()
        presenter.output = viewController
        
        let interactor = PersonsInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
