//
//  PersonsPresenter.swift
//  cleanSwift_example
//
//  Created by Oliver Mastny on 06/01/2017.
//  Copyright (c) 2017 Oliver Mastny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PersonsPresenterInput {
    func show(response: Persons.FetchPersons.Response)
}

protocol PersonsPresenterOutput: class {
    func show(viewModel: Persons.FetchPersons.ViewModel)
    func personsRemoved()
}

class PersonsPresenter: PersonsPresenterInput {
    weak var output: PersonsPresenterOutput!
    
    func show(response: Persons.FetchPersons.Response) {
        var displayedPersons: [Persons.FetchPersons.ViewModel.DisplayPerson] = []
        for person in response.persons {
            let isCreated = person.isCreated?.getString(withDateFormatType: .long)
            let displayPerson = Persons.FetchPersons.ViewModel.DisplayPerson(firstname: person.firstname, lastname: person.lastname, isCreated: isCreated)
            displayedPersons.append(displayPerson)
        }
        let viewModel = Persons.FetchPersons.ViewModel(displayedPersons: displayedPersons)
        output.show(viewModel: viewModel)
    }
    
    func personsRemoved() {
        output.personsRemoved()
    }
}
